"""Domain enumerations. Values are persisted and exposed via the API; never rename a value in place."""

from enum import StrEnum


class CaseStatus(StrEnum):
    RECEIVED = "RECEIVED"
    INFORMATION_COLLECTION = "INFORMATION_COLLECTION"
    VALIDATION = "VALIDATION"
    RULE_EVALUATION = "RULE_EVALUATION"
    PENDING_INFORMATION = "PENDING_INFORMATION"
    RECOMMENDATION_READY = "RECOMMENDATION_READY"
    PENDING_HUMAN_REVIEW = "PENDING_HUMAN_REVIEW"
    ESCALATED = "ESCALATED"
    APPROVED = "APPROVED"
    DENIED = "DENIED"
    CLOSED = "CLOSED"


class Urgency(StrEnum):
    STANDARD = "STANDARD"
    EXPEDITED = "EXPEDITED"


class DecisionClass(StrEnum):
    """Whether the benefit schedule can decide a procedure, or a human must."""

    CLEAR = "CLEAR"
    EXCLUDED = "EXCLUDED"
    AMBIGUOUS = "AMBIGUOUS"


class DirectoryStatus(StrEnum):
    ACTIVE = "ACTIVE"
    SUSPENDED = "SUSPENDED"
    PENDING_ONBOARDING = "PENDING_ONBOARDING"


class DocumentType(StrEnum):
    REFERRAL_LETTER = "REFERRAL_LETTER"
    CLINICAL_NOTES = "CLINICAL_NOTES"
    IMAGING_REPORT = "IMAGING_REPORT"
    LAB_RESULTS = "LAB_RESULTS"
    PRIOR_TREATMENT_RECORD = "PRIOR_TREATMENT_RECORD"
    OPERATIVE_PLAN = "OPERATIVE_PLAN"


class ActorType(StrEnum):
    PROVIDER_PORTAL = "PROVIDER_PORTAL"
    VOICE_AGENT = "VOICE_AGENT"
    SYSTEM = "SYSTEM"
    HUMAN_REVIEWER = "HUMAN_REVIEWER"


class ReviewerRole(StrEnum):
    CLINICAL_REVIEWER = "CLINICAL_REVIEWER"
    MEDICAL_DIRECTOR = "MEDICAL_DIRECTOR"


class ReviewQueue(StrEnum):
    CLINICAL_REVIEW = "CLINICAL_REVIEW"
    MEDICAL_DIRECTOR_REVIEW = "MEDICAL_DIRECTOR_REVIEW"


class RuleOutcome(StrEnum):
    PASS = "PASS"
    FAIL = "FAIL"
    UNKNOWN = "UNKNOWN"


class RuleCategory(StrEnum):
    ELIGIBILITY = "ELIGIBILITY"
    NETWORK = "NETWORK"
    COVERAGE = "COVERAGE"
    DOCUMENTATION = "DOCUMENTATION"
    LIMITS = "LIMITS"


class MissingInformationSource(StrEnum):
    """Who is able to supply a missing piece of information."""

    PROVIDER = "PROVIDER"
    INSURER = "INSURER"


class RecommendationOutcome(StrEnum):
    RECOMMEND_APPROVAL = "RECOMMEND_APPROVAL"
    RECOMMEND_DENIAL = "RECOMMEND_DENIAL"
    REQUEST_MORE_INFORMATION = "REQUEST_MORE_INFORMATION"
    ESCALATE = "ESCALATE"


class HumanDecisionType(StrEnum):
    APPROVE = "APPROVE"
    DENY = "DENY"
    REQUEST_INFORMATION = "REQUEST_INFORMATION"
    ESCALATE = "ESCALATE"


class CloseReason(StrEnum):
    WITHDRAWN_BY_PROVIDER = "WITHDRAWN_BY_PROVIDER"
    DECISION_COMMUNICATED = "DECISION_COMMUNICATED"


class PolicyStatus(StrEnum):
    ACTIVE = "ACTIVE"
    LAPSED = "LAPSED"


class AuditEventType(StrEnum):
    CASE_CREATED = "CASE_CREATED"
    CASE_STATUS_CHANGED = "CASE_STATUS_CHANGED"
    INFORMATION_COLLECTED = "INFORMATION_COLLECTED"
    INFORMATION_MODIFIED = "INFORMATION_MODIFIED"
    DOCUMENT_REGISTERED = "DOCUMENT_REGISTERED"
    VALIDATION_PASSED = "VALIDATION_PASSED"
    VALIDATION_FAILED = "VALIDATION_FAILED"
    RULES_EVALUATED = "RULES_EVALUATED"
    RECOMMENDATION_GENERATED = "RECOMMENDATION_GENERATED"
    HUMAN_REVIEW_REQUESTED = "HUMAN_REVIEW_REQUESTED"
    CASE_ESCALATED = "CASE_ESCALATED"
    REVIEWER_ASSIGNED = "REVIEWER_ASSIGNED"
    HUMAN_DECISION_RECORDED = "HUMAN_DECISION_RECORDED"
    RECOMMENDATION_OVERRIDDEN = "RECOMMENDATION_OVERRIDDEN"
    CASE_CLOSED = "CASE_CLOSED"
    CALL_SUMMARY_LOGGED = "CALL_SUMMARY_LOGGED"
    HUMAN_CALLBACK_REQUESTED = "HUMAN_CALLBACK_REQUESTED"
    HUMAN_CALLBACK_RESOLVED = "HUMAN_CALLBACK_RESOLVED"
    CALL_RECORDED = "CALL_RECORDED"


class CallerRole(StrEnum):
    """Who is on the line. Only provider staff and brokers acting for a provider may open pre-auth cases."""

    PROVIDER_STAFF = "PROVIDER_STAFF"
    BROKER = "BROKER"
    SUPPLIER = "SUPPLIER"
    OTHER = "OTHER"


CASE_CALLER_ROLES = frozenset({CallerRole.PROVIDER_STAFF, CallerRole.BROKER})


class CallbackReason(StrEnum):
    NON_STANDARD_REQUEST = "NON_STANDARD_REQUEST"
    CALLER_REQUESTED_HUMAN = "CALLER_REQUESTED_HUMAN"
    SUPPLIER_ENQUIRY = "SUPPLIER_ENQUIRY"
    URGENT_CLINICAL = "URGENT_CLINICAL"
    COMPLAINT = "COMPLAINT"
    UNSUPPORTED_LANGUAGE = "UNSUPPORTED_LANGUAGE"
    OTHER = "OTHER"


class CallOutcome(StrEnum):
    """What the caller was told at the end of the call, as recorded by log_transcript."""

    RECOMMENDATION_PREPARED = "RECOMMENDATION_PREPARED"
    MORE_INFORMATION_REQUESTED = "MORE_INFORMATION_REQUESTED"
    ESCALATED = "ESCALATED"
    CALLER_NOT_VERIFIED = "CALLER_NOT_VERIFIED"
    ONBOARDING_ENQUIRY = "ONBOARDING_ENQUIRY"
    OUT_OF_SCOPE = "OUT_OF_SCOPE"


class CallbackStatus(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"
