"""Bring the hosted (ElevenLabs) deployment up with one command: ``./scripts/run_hosted.sh``.

Orchestration only. Every step calls something that already exists — the backend, ``verify_deployment.py``,
``elevenlabs_setup.py`` — or one documented ElevenLabs endpoint. Nothing here touches cases, rules or prompts.

    a. start the backend
    b. start the Cloudflare named tunnel, and wait until the public URL answers
    c. verify the deployment through the public URL; stop if anything fails
    d. create or update the ElevenLabs agent, tools, knowledge base and keyterms
    e. register the post-call webhook and point the workspace at it
    f. import the Twilio number and assign it to the agent, when one is configured
    g. print what is live, then keep both processes running until Ctrl+C

Configuration comes from ``.env``; see ``.env.example``. Values this script generates (the voice-tool token, the
gateway secret and the webhook signing secret) are kept in ``.hosted/secrets.env``, which is git-ignored and is
never read by local mode.
"""

import argparse
import getpass
import json
import os
import re
import secrets
import shutil
import signal
import socket
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".env"
HOSTED_DIR = ROOT / ".hosted"
SECRETS_FILE = HOSTED_DIR / "secrets.env"
STATE_FILE = ROOT / ".elevenlabs-state.json"  # shared with elevenlabs_setup.py; unknown keys are preserved
API = os.environ.get("PREAUTH_ELEVENLABS_API_BASE", "https://api.elevenlabs.io").rstrip("/")

WEBHOOK_PATH = "/api/v1/voice/elevenlabs/post-call"
WEBHOOK_NAME = "sawt-al-tameen post-call"
DASHBOARD = {
    "agents_settings": "https://elevenlabs.io/app/agents/settings",
    "phone_numbers": "https://elevenlabs.io/app/agents/phone-numbers",
    "api_keys": "https://elevenlabs.io/app/settings/api-keys",
}
_PLACEHOLDER = re.compile(r"^(|<.*>|your[-_ ].*|changeme|x+|\.\.\.)$", re.IGNORECASE)
_E164 = re.compile(r"^\+[1-9][0-9]{7,14}$")


class Stop(Exception):
    """A step failed in a way the operator must fix. Carries the explanation; never a stack trace."""


# --------------------------------------------------------------------------- output


def step(letter: str, title: str) -> None:
    print(f"\n\033[1m[{letter}] {title}\033[0m", flush=True)


def ok(text: str) -> None:
    print(f"    \033[32mPASS\033[0m  {text}", flush=True)


def info(text: str) -> None:
    print(f"          {text}", flush=True)


def warn(text: str) -> None:
    print(f"    \033[33mWARN\033[0m  {text}", flush=True)


def banner(text: str, colour: str) -> None:
    code = {"green": "32", "red": "31", "yellow": "33"}[colour]
    line = "=" * 78
    print(f"\n\033[{code}m{line}\n  {text}\n{line}\033[0m", flush=True)


# --------------------------------------------------------------------------- configuration


def read_env_file(path: Path) -> dict[str, str]:
    """KEY=VALUE lines. Inline ``# comments`` after whitespace are dropped; quotes are stripped."""
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw in path.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = re.split(r"\s+#", value, maxsplit=1)[0].strip().strip('"').strip("'")
        values[key.strip()] = value
    return values


def load_config() -> dict[str, str]:
    """Precedence: the real environment, then .env, then values this script generated earlier."""
    config = read_env_file(SECRETS_FILE)
    config.update({k: v for k, v in read_env_file(ENV_FILE).items() if v})
    config.update({k: v for k, v in os.environ.items() if v})
    return config


def is_set(config: dict[str, str], name: str) -> bool:
    return not _PLACEHOLDER.match(config.get(name, "").strip())


def remember_secret(config: dict[str, str], name: str, value: str) -> None:
    HOSTED_DIR.mkdir(exist_ok=True)
    existing = read_env_file(SECRETS_FILE)
    existing[name] = value
    lines = ["# Generated by scripts/run_hosted.sh. Git-ignored. Delete a line to have it regenerated."]
    lines += [f"{k}={v}" for k, v in existing.items()]
    SECRETS_FILE.write_text("\n".join(lines) + "\n")
    SECRETS_FILE.chmod(0o600)
    config[name] = value


# --------------------------------------------------------------------------- ElevenLabs


def elevenlabs(config: dict[str, str], method: str, path: str, body: dict[str, Any] | None = None) -> Any:
    request = urllib.request.Request(
        API + path,
        method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"xi-api-key": config["ELEVENLABS_API_KEY"], "content-type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            raw = response.read()
            return json.loads(raw) if raw else {}
    except urllib.error.HTTPError as e:
        detail = e.read().decode(errors="replace")[:600]
        if e.code == 401:
            raise Stop(
                "ElevenLabs rejected ELEVENLABS_API_KEY (HTTP 401).\n"
                f"          Create a key at {DASHBOARD['api_keys']} with access to ElevenAgents, put it in .env,\n"
                f"          and run again.\n          ElevenLabs said: {detail}"
            ) from None
        raise Stop(f"ElevenLabs API {method} {path} failed with HTTP {e.code}:\n          {detail}") from None
    except urllib.error.URLError as e:
        raise Stop(f"Could not reach the ElevenLabs API at {API}: {e.reason}. Check the network.") from None


def load_state() -> dict[str, Any]:
    return json.loads(STATE_FILE.read_text()) if STATE_FILE.exists() else {}


def save_state(state: dict[str, Any]) -> None:
    STATE_FILE.write_text(json.dumps(state, indent=2))


# --------------------------------------------------------------------------- processes


class Processes:
    def __init__(self) -> None:
        self.children: dict[str, subprocess.Popen] = {}

    def start(self, name: str, command: list[str], env: dict[str, str]) -> subprocess.Popen:
        HOSTED_DIR.mkdir(exist_ok=True)
        log = open(HOSTED_DIR / f"{name}.log", "ab")
        process = subprocess.Popen(
            command, cwd=ROOT, env=env, stdout=log, stderr=subprocess.STDOUT, start_new_session=True
        )
        self.children[name] = process
        return process

    def stop(self, name: str) -> None:
        process = self.children.pop(name, None)
        if process and process.poll() is None:
            os.killpg(process.pid, signal.SIGTERM)
            try:
                process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                os.killpg(process.pid, signal.SIGKILL)

    def stop_all(self) -> None:
        for name in list(self.children):
            self.stop(name)

    def exited(self) -> str | None:
        return next((n for n, p in self.children.items() if p.poll() is not None), None)


def log_tail(name: str, lines: int = 15) -> str:
    path = HOSTED_DIR / f"{name}.log"
    if not path.exists():
        return "(no log)"
    return "\n".join("          | " + l for l in path.read_text(errors="replace").splitlines()[-lines:])


def http_status(url: str, timeout: float = 5) -> tuple[int | None, str]:
    try:
        with urllib.request.urlopen(url, timeout=timeout) as response:
            return response.status, response.read(200).decode(errors="replace")
    except urllib.error.HTTPError as e:
        return e.code, ""
    except (urllib.error.URLError, OSError, TimeoutError):
        return None, ""


def port_free(port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as probe:
        probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            probe.bind(("127.0.0.1", port))
        except OSError:
            return False
    return True


# --------------------------------------------------------------------------- steps


def preflight(config: dict[str, str], args: argparse.Namespace) -> None:
    step("0", "Checking .env")
    if not ENV_FILE.exists():
        raise Stop("No .env file. Run:  cp .env.example .env  then fill in the HOSTED MODE section.")

    problems = []
    if not is_set(config, "ELEVENLABS_API_KEY"):
        problems.append(f"ELEVENLABS_API_KEY is empty — create one at {DASHBOARD['api_keys']}")
    if not args.no_tunnel:
        if not is_set(config, "CLOUDFLARE_TUNNEL_TOKEN"):
            problems.append("CLOUDFLARE_TUNNEL_TOKEN is empty — see the ONE-TIME tunnel steps in .env.example")
        if shutil.which("cloudflared") is None:
            problems.append("cloudflared is not installed — https://developers.cloudflare.com/cloudflare-one/"
                            "networks/connectors/cloudflare-tunnel/downloads/")
    base_url = config.get("PREAUTH_PUBLIC_BASE_URL", "").strip().rstrip("/")
    if not is_set(config, "PREAUTH_PUBLIC_BASE_URL"):
        problems.append("PREAUTH_PUBLIC_BASE_URL is empty — the https:// hostname you gave the tunnel")
    elif not args.no_tunnel and not base_url.startswith("https://"):
        problems.append(f"PREAUTH_PUBLIC_BASE_URL must start with https:// (got {base_url!r})")

    twilio = [n for n in ("TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER") if is_set(config, n)]
    if twilio and len(twilio) < 3:
        missing = sorted({"TWILIO_ACCOUNT_SID", "TWILIO_AUTH_TOKEN", "TWILIO_PHONE_NUMBER"} - set(twilio))
        problems.append(f"Twilio is half-configured; also set {', '.join(missing)} (or clear all three)")
    if is_set(config, "TWILIO_PHONE_NUMBER") and not _E164.match(config["TWILIO_PHONE_NUMBER"].replace(" ", "")):
        problems.append("TWILIO_PHONE_NUMBER must be in international format, e.g. +14155550123")

    if problems:
        raise Stop("Fix these in .env and run again:\n" + "\n".join(f"          - {p}" for p in problems))
    config["PREAUTH_PUBLIC_BASE_URL"] = base_url
    ok(".env has everything this run needs")

    # Fail fast on a bad key, before anything is started.
    elevenlabs(config, "GET", "/v1/convai/agents?page_size=1")
    ok("ElevenLabs accepted the API key")

    for name in ("PREAUTH_VOICE_AGENT_TOKEN", "PREAUTH_GATEWAY_SECRET"):
        if not is_set(config, name):
            remember_secret(config, name, secrets.token_urlsafe(32))
            info(f"generated {name} (kept in .hosted/secrets.env)")

    port = int(config.get("PREAUTH_HOSTED_PORT") or 8000)
    if not port_free(port):
        raise Stop(
            f"Port {port} is in use. The tunnel forwards to a fixed port (the Service URL you set in Cloudflare),\n"
            f"          so this cannot move to another one automatically. Stop whatever is on {port}, or set\n"
            f"          PREAUTH_HOSTED_PORT in .env and change the tunnel's Service URL to match."
        )
    config["PREAUTH_HOSTED_PORT"] = str(port)


def backend_env(config: dict[str, str]) -> dict[str, str]:
    env = {**os.environ, **config}
    env["PREAUTH_RUNTIME_MODE"] = "elevenlabs"
    env.pop("CLOUDFLARE_TUNNEL_TOKEN", None)
    env.pop("TUNNEL_TOKEN", None)
    return env


def start_backend(config: dict[str, str], processes: Processes) -> None:
    env = backend_env(config)
    for command in (
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        [sys.executable, "-m", "preauth.seed", "--if-empty"],
    ):
        result = subprocess.run(command, cwd=ROOT, env=env, capture_output=True, text=True)
        if result.returncode != 0:
            raise Stop(f"{' '.join(command[2:])} failed:\n{result.stdout}{result.stderr}")
    info("database migrated and catalogue present")

    port = config["PREAUTH_HOSTED_PORT"]
    processes.start(
        "backend",
        [sys.executable, "-m", "uvicorn", "preauth.main:app", "--host", "127.0.0.1", "--port", port,
         "--proxy-headers", "--forwarded-allow-ips", "*"],
        env,
    )
    for _ in range(60):
        if http_status(f"http://127.0.0.1:{port}/health")[0] == 200:
            ok(f"backend is serving on http://127.0.0.1:{port} (log: .hosted/backend.log)")
            return
        if processes.exited() == "backend":
            break
        time.sleep(0.5)
    raise Stop(f"The backend did not start.\n{log_tail('backend')}")


def start_tunnel(config: dict[str, str], processes: Processes) -> None:
    env = {**os.environ, "TUNNEL_TOKEN": config["CLOUDFLARE_TUNNEL_TOKEN"]}  # via env, never on the command line
    processes.start("tunnel", ["cloudflared", "tunnel", "--no-autoupdate", "run"], env)
    public = config["PREAUTH_PUBLIC_BASE_URL"]
    info(f"waiting for {public} to answer (up to 90 s)")
    bad_token = (
        "Cloudflare rejected CLOUDFLARE_TUNNEL_TOKEN (cloudflared: \"Failed to get tunnel\"). The token is\n"
        "          wrong, truncated, or the tunnel was deleted. Copy it again: Cloudflare dashboard → Networking →\n"
        "          Tunnels → your tunnel → the token in the install command.\n"
    )
    last = None
    for _ in range(45):
        log = (HOSTED_DIR / "tunnel.log").read_text(errors="replace") if (HOSTED_DIR / "tunnel.log").exists() else ""
        # cloudflared does not exit on a bad token; it retries forever. Read its log instead of waiting it out.
        if log.count("Register tunnel error") >= 2 or "Unauthorized" in log or "Invalid tunnel secret" in log:
            raise Stop(bad_token + log_tail("tunnel", 4))
        if processes.exited() == "tunnel":
            raise Stop(f"cloudflared exited.\n{log_tail('tunnel')}")
        last, body = http_status(f"{public}/health", timeout=8)
        if last == 200 and '"ok"' in body:
            ok(f"tunnel is up: {public} reaches this backend (log: .hosted/tunnel.log)")
            return
        time.sleep(2)
    if "Registered tunnel connection" not in log:
        raise Stop(f"cloudflared never connected to Cloudflare in 90 s. Check the network.\n{log_tail('tunnel')}")
    hint = {
        502: "Cloudflare reached the tunnel but not the backend: the hostname's Service URL must be "
             f"http://localhost:{config['PREAUTH_HOSTED_PORT']}",
        404: "the hostname answers but is not routed to this tunnel — check the Public Hostname entry",
        530: "the hostname is not connected to a running tunnel — check the hostname belongs to THIS tunnel",
        None: "the hostname does not resolve or answer — check PREAUTH_PUBLIC_BASE_URL matches the hostname "
              "you published",
    }.get(last, f"got HTTP {last}")
    raise Stop(f"{public}/health never answered: {hint}.\n{log_tail('tunnel')}")


def verify(config: dict[str, str], label: str) -> None:
    print(f"          running scripts/verify_deployment.py against {config['PREAUTH_PUBLIC_BASE_URL']}\n")
    result = subprocess.run(
        [sys.executable, "scripts/verify_deployment.py", "--base-url", config["PREAUTH_PUBLIC_BASE_URL"]],
        cwd=ROOT, env=backend_env(config), capture_output=True, text=True,
    )
    output = result.stdout + result.stderr
    print("\n".join("      " + l for l in output.rstrip().splitlines()))
    counts = re.search(r"(\d+) passed, (\d+) failed", output)
    summary = f"{counts.group(1)} passed, {counts.group(2)} failed" if counts else "no summary line"
    if result.returncode != 0:
        failed = [l.strip() for l in output.splitlines() if l.strip().startswith("FAIL")]
        banner(f"VERIFY ({label}): FAIL — {summary}. Nothing further was changed in ElevenLabs.", "red")
        raise Stop("These checks failed:\n" + "\n".join(f"          {l}" for l in failed or [output[-400:]]))
    banner(f"VERIFY ({label}): PASS — {summary}", "green")


def setup_agent(config: dict[str, str]) -> str:
    result = subprocess.run(
        [sys.executable, "scripts/elevenlabs_setup.py"], cwd=ROOT, env=backend_env(config),
        capture_output=True, text=True,
    )
    for line in (result.stdout + result.stderr).splitlines():
        if line.startswith(("secret:", "tool:", "knowledge base:", "agent:")):
            info(line)
    if result.returncode != 0:
        raise Stop(f"elevenlabs_setup.py failed:\n          {(result.stderr or result.stdout).strip()[-800:]}")
    agent_id = load_state().get("agent_id")
    if not agent_id:
        raise Stop("elevenlabs_setup.py finished but recorded no agent_id in .elevenlabs-state.json")
    ok(f"agent {agent_id}: system prompt, 3 server tools, knowledge base, keyterm biasing")
    return agent_id


def register_webhook(config: dict[str, str], args: argparse.Namespace) -> bool:
    """Returns True when the backend must be restarted to pick up a new signing secret."""
    url = config["PREAUTH_PUBLIC_BASE_URL"] + WEBHOOK_PATH
    state = load_state()
    saved = state.get("post_call_webhook") or {}
    have_secret = is_set(config, "PREAUTH_ELEVENLABS_WEBHOOK_SECRET")
    restart = False

    if saved.get("id") and have_secret:
        if saved.get("url") != url:
            elevenlabs(config, "PATCH", f"/v1/workspace/webhooks/{saved['id']}",
                       {"settings": {"name": WEBHOOK_NAME, "webhook_url": url}})
            info(f"webhook {saved['id']}: URL updated to {url}")
        else:
            info(f"webhook {saved['id']}: already registered for {url}")
        webhook_id = saved["id"]
    else:
        created = elevenlabs(config, "POST", "/v1/workspace/webhooks",
                             {"settings": {"auth_type": "hmac", "name": WEBHOOK_NAME, "webhook_url": url}})
        webhook_id = created["webhook_id"]
        # Saved before anything can stop the run, so a re-run reuses this webhook instead of creating another.
        state["post_call_webhook"] = {"id": webhook_id, "url": url}
        save_state(state)
        secret = created.get("webhook_secret")
        if not secret:
            secret = ask_for_webhook_secret(url)
        remember_secret(config, "PREAUTH_ELEVENLABS_WEBHOOK_SECRET", secret)
        info(f"webhook {webhook_id}: created for {url}; signing secret kept in .hosted/secrets.env")
        restart = True
    state["post_call_webhook"] = {"id": webhook_id, "url": url}
    save_state(state)

    current = (elevenlabs(config, "GET", "/v1/convai/settings").get("webhooks") or {}).get("post_call_webhook_id")
    if current and current != webhook_id and current not in state.get("previous_webhook_ids", []):
        warn(f"this ElevenLabs workspace already sends post-call webhooks to another endpoint ({current}).")
        info("The setting is workspace-wide: switching it moves every agent's transcripts here.")
        if not confirm("Point the workspace's post-call webhook at this backend?", args):
            raise Stop(
                "Left the existing webhook alone. Without it, reviewers stay blocked (CALL_RECORD_PENDING).\n"
                f"          Either re-run with --yes, or set it per agent at {DASHBOARD['agents_settings']}."
            )
    if current != webhook_id:
        elevenlabs(config, "PATCH", "/v1/convai/settings",
                   {"webhooks": {"post_call_webhook_id": webhook_id, "events": ["transcript"],
                                 "transcript_format": "json"}})
        state.setdefault("previous_webhook_ids", []).append(webhook_id)
        save_state(state)
    ok(f"post-call transcripts are sent to {url}")
    return restart


def ask_for_webhook_secret(url: str) -> str:
    """Manual fallback: ElevenLabs created the webhook but did not return its secret in the response."""
    warn("ElevenLabs created the webhook but did not return its signing secret.")
    info(f"Open {DASHBOARD['agents_settings']} → Post-call webhook, find the webhook for")
    info(f"{url}, and copy its signing secret.")
    if not sys.stdin.isatty():
        raise Stop("Cannot prompt without a terminal. Put the secret in .env as "
                   "PREAUTH_ELEVENLABS_WEBHOOK_SECRET and run again.")
    while True:
        value = getpass.getpass("          Paste the signing secret (input hidden): ").strip()
        if value:
            return value


def confirm(question: str, args: argparse.Namespace) -> bool:
    if args.yes:
        return True
    if not sys.stdin.isatty():
        return False
    return input(f"          {question} [y/N] ").strip().lower() in ("y", "yes")


def wire_phone_number(config: dict[str, str], agent_id: str) -> str | None:
    if not is_set(config, "TWILIO_PHONE_NUMBER"):
        warn("no TWILIO_PHONE_NUMBER in .env — phone calling is off; the browser test call still works.")
        for line in (
            "To take real calls (ONE-TIME):",
            "  1. Sign up at https://www.twilio.com/try-twilio (trial accounts include credit).",
            "  2. Console → Phone Numbers → Manage → Buy a number (Voice-capable).",
            "  3. Console → Account → API keys & tokens: copy Account SID and Auth Token.",
            "  4. Put TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER in .env and re-run;",
            f"     this script then imports it. (Manual alternative: {DASHBOARD['phone_numbers']} → Import.)",
            "  Trial numbers only take calls from numbers you verify in Twilio, and play a trial notice.",
        ):
            info(line)
        return None

    number = config["TWILIO_PHONE_NUMBER"].replace(" ", "")
    state = load_state()
    listed = elevenlabs(config, "GET", "/v1/convai/phone-numbers")
    items = listed if isinstance(listed, list) else listed.get("phone_numbers", [])
    existing = next((p for p in items if (p.get("phone_number") or "").replace(" ", "") == number), None)
    if existing:
        phone_id = existing["phone_number_id"]
        assigned = (existing.get("assigned_agent") or {}).get("agent_id")
        if assigned != agent_id:
            elevenlabs(config, "PATCH", f"/v1/convai/phone-numbers/{phone_id}", {"agent_id": agent_id})
            info(f"phone {number}: reassigned to the agent")
        else:
            info(f"phone {number}: already assigned to the agent")
    else:
        created = elevenlabs(config, "POST", "/v1/convai/phone-numbers", {
            "provider": "twilio", "phone_number": number, "label": "Sawt Assurance pre-authorisation line",
            "sid": config["TWILIO_ACCOUNT_SID"], "token": config["TWILIO_AUTH_TOKEN"], "agent_id": agent_id,
        })
        phone_id = created["phone_number_id"]
        # Some API versions ignore agent_id on import; assigning explicitly makes the result certain.
        elevenlabs(config, "PATCH", f"/v1/convai/phone-numbers/{phone_id}", {"agent_id": agent_id})
        info(f"phone {number}: imported from Twilio and assigned to the agent")
    state["phone_number"] = {"id": phone_id, "number": number}
    save_state(state)
    ok(f"calls to {number} are answered by the agent")
    return number


# --------------------------------------------------------------------------- main


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--yes", action="store_true", help="answer yes to confirmation prompts")
    parser.add_argument(
        "--no-tunnel", action="store_true",
        help="do not start cloudflared; PREAUTH_PUBLIC_BASE_URL already reaches this machine some other way",
    )
    args = parser.parse_args()

    config = load_config()
    processes = Processes()
    # Fresh logs per run: the tunnel check reads its log, and yesterday's errors must not fail today's run.
    for name in ("backend", "tunnel"):
        (HOSTED_DIR / f"{name}.log").unlink(missing_ok=True)

    def shutdown(*_: object) -> None:
        raise KeyboardInterrupt

    signal.signal(signal.SIGTERM, shutdown)
    try:
        preflight(config, args)

        step("a", "Starting the backend")
        start_backend(config, processes)

        step("b", "Starting the Cloudflare tunnel")
        if args.no_tunnel:
            info("--no-tunnel: using PREAUTH_PUBLIC_BASE_URL as given")
        else:
            start_tunnel(config, processes)

        step("c", "Verifying the deployment through the public URL")
        verify(config, "initial")

        step("d", "Configuring the ElevenLabs agent")
        agent_id = setup_agent(config)

        step("e", "Registering the post-call webhook")
        if register_webhook(config, args):
            info("restarting the backend so it verifies webhook signatures with the new secret")
            processes.stop("backend")
            start_backend(config, processes)
            step("e", "Re-verifying, now including the post-call webhook")
            verify(config, "with webhook")

        step("f", "Phone number")
        number = wire_phone_number(config, agent_id)

        step("g", "Summary")
        talk = f"https://elevenlabs.io/app/talk-to?agent_id={agent_id}"
        banner("LIVE — Sawt Assurance pre-authorisation line", "green")
        print(f"  Backend          {config['PREAUTH_PUBLIC_BASE_URL']}   (API docs: /docs)")
        print(f"  Test in browser  {talk}")
        print(f"  Phone            {number or 'not configured (see step f above)'}")
        print(f"  Transcripts      {config['PREAUTH_PUBLIC_BASE_URL']}{WEBHOOK_PATH}")
        print("  Logs             .hosted/backend.log, .hosted/tunnel.log")
        print("\n  Still manual, optional (docs/VOICE_AGENT.md): the visual workflow with per-node tool scoping,")
        print("  evaluation criteria, and dashboard agent tests. None is needed for calls to work.")
        print("\n  Running. Press Ctrl+C to stop the backend and the tunnel.", flush=True)

        while True:
            gone = processes.exited()
            if gone:
                raise Stop(f"The {gone} process exited unexpectedly.\n{log_tail(gone)}")
            time.sleep(1)
    except Stop as e:
        banner("STOPPED", "red")
        print(f"          {e}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nStopping.")
        return 0
    finally:
        # A second Ctrl+C (or a forwarded SIGTERM) must not interrupt the cleanup and leave a process behind.
        signal.signal(signal.SIGINT, signal.SIG_IGN)
        signal.signal(signal.SIGTERM, signal.SIG_IGN)
        processes.stop_all()


if __name__ == "__main__":
    raise SystemExit(main())
